workflows:
  flutter-ios-workflow:
    name: Flutter Web Shooter Build
    instance_type: mac_mini_m2
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter Packages
        script: flutter pub get
      - name: Build Flutter Web App
        script: |
          flutter build web --release
      - name: Compress Web Output
        script: |
          cd build/web
          zip -r ../../web-game.zip .
    artifacts:
      - web-game.zip
